// Remova a diretiva "use client" aqui
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Definindo as fontes
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Visite.la",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <ul style={{ listStyle: "none", padding: 0, margin: 0, background: "#000" }}>
            <li>
              <a
                href="https://github.com/davinyleticia/visitela-frotend"
                rel="noopener noreferrer"
                style={{
                  color: "#fff",
                  textDecoration: "none",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  marginBottom: "1rem",
                  padding: "12px 16px",
                }}
              >
                Repositório do Projeto GitHub
              </a>
            </li>
          </ul>
        </nav>


        {children}
      </body>
    </html>
  );
}
